Car_Rental_Site/Car_Rental_Site/Controllers/SearchByDatesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BL;
using Model;
using System.Net;




namespace Car_Rental_Site.Controllers
{
    public class SearchByDatesController : Controller
    {
        /// <summary>
        /// Search vehicles for rent - view page
        /// In this page the user can search vehicles for rent by to dates and filter the results by JS - jquery
        /// 
        /// For the filter this action connects to the DB - if he can't connect "CriticalError" rising and the user redirect to the home page
        /// In this way the user can't start search if the server has problems.
        /// </summary>
        /// <returns>The search vehicles page</returns>
        public ActionResult Search()
        {
            try
            {
            using (VehiclesTypesLogic logic = new VehiclesTypesLogic())
            {
                ViewBag.ManufacturersList = logic.listOfManufacturer();
                ViewBag.ModelsList = logic.listOfModels();
                ViewBag.YearsList = logic.listOfYears();
                return View();
            }
            }
            catch (Exception)
            {
                ViewBag.Error = "We have problem on the server, Please try again later!";
                ViewBag.CriticalError = true;
                ViewBag.ManufacturersList = new List<string>();
                ViewBag.ModelsList = new List<string>();
                ViewBag.YearsList = new List<int>();
                return View(new VehiclesType());
            }
        }

        /// <summary>
        /// Return all vehicles that available for rent between two dates
        /// All the logic to know if the vehicle available or not supplied in the BL 
        /// 
        /// After this The filter menu displayed
        /// </summary>
        /// <param name="startDate">The start date</param>
        /// <param name="endDate">The end date</param>
        /// <returns>To ajax list of vehicle types / BadRequest</returns>
        public ActionResult SearchResults(DateTime? startDate, DateTime? endDate)
        {
            try
            {
            SearchLogic logic = new SearchLogic();
            return Json(logic.SearchByDates(startDate.Value, endDate.Value), JsonRequestBehavior.AllowGet);
            }
            catch (Exception)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest, "We have problem on the server, Please try again later!");
            }
        }

    }
}

Car_Rental_Site/Car_Rental_Site/Views/Shared/_Layout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html lang="en">
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />


    <link href="~/Content/themes/smoothness/jquery-ui-1.10.3.custom.css" rel="stylesheet" />
   
    <link href="~/Content/Site.css" rel="stylesheet" />



    @RenderSection("styles", required: false)
    <style>
        .template {
            display: none;
        }
    </style>

</head>
<body>
    <header>
        <h1>Car Rental Company</h1>
        

        <div class="content-wrapper">
            <div class="float-left">
                <p class="site-title">
                    <a href="~/">
                        <img src="~/Images/logo.png" alt="logo" />
                    </a>
                </p>
            </div>
            <div class="float-right">
                <section id="login">
                    @Html.Partial("_LoginPartial")
                </section>
                <nav>
                    @Html.Partial("_MenuPartial")
                </nav>
            </div>
        </div>

    </header>
    <nav></nav>
    <main>
        <div id="body">
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>
    </main>
    <footer>
        <div class="content-wrapper">
            <div class="float-left">
                <p>
                    &copy; All rights reserved to - Car Rental Company Ltd.
                    <br />
                    &copy; Built by Olivia Frumin as final MVC project @DateTime.Now.Year
                </p>
            </div>
        </div>
    </footer>

    <div id="ServerErrorMessages" title="Server Error!">
        <p id="ErrorMessage"></p>
    </div>

    @RenderSection("scripts", required: false)

    @* IF there is a problem on the server *@
    @if (ViewBag.Error != null)
    {
        <script>
            $(function () {
                //if the problem is critical the user redirect to the home page
                @if (ViewBag.CriticalError != null)
                {
                  <text>openErrorsDialog('@ViewBag.Error', true)</text>
                }
                //if the problem is not critical the page displayed but error message  displayed first
                else
                {
                  <text>openErrorsDialog('@ViewBag.Error',false)</text>
                }
            });
        </script>
    }

    
    <script src="~/Scripts/jquery-1.9.1.js"></script>
    <script src="~/Scripts/jquery-ui-1.10.3.custom.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
    <script src="~/Scripts/jquery.validate-vsdoc.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>

    <script src="~/Scripts/ErrorMessages.js"></script>

    <script src="~/Scripts/bootstrap.js"></script>

</body>
</html>

Car_Rental_Site/Car_Rental_Site/Views/Shared/_MenuPartial.cshtml
<ul id="menu">
    <li>@Html.ActionLink("Home", "Index", "Home", new { Area = "" }, "")</li>
    <li>@Html.ActionLink("Search cars", "Search", "SearchByDates", new { Area = "" }, "")</li>
    <li>@Html.ActionLink("About", "About", "Home", new { Area = "" }, "")</li>
    <li>@Html.ActionLink("Contact", "Contact", "Home", new { Area = "" }, "")</li>
    @if (User.IsInRole("Admin"))
    {
        <li>@Html.ActionLink("Manage", "index", new { Area = "Manage", Controller = "MangeHome", action = "index" }, "")</li>
    }
    @if (User.IsInRole("Employee"))
    {
        <li>@Html.ActionLink("Manage", "index", new { Area = "Employee", Controller = "ReturnVehicle", action = "index" }, "")</li>
    }
    @if (User.IsInRole("User"))
    {
        <li>@Html.ActionLink("Manage your account", "ManageAccount", new { Area = "", Controller = "Account", action = "ManageAccount" }, "")</li>
    }
   
</ul>